# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
    - main
    paths:
    - 'assignment02/**'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Setting Working Directory
      run: cd ./assignment02

    - name: Go Mod Tidy
        working-directory: ./assignment02
        run: go mod tidy

    - name: Build
        working-directory: ./assignment02
        run: go build -v ./...
